src/objects/Transaction_Entry__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>14</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Transactions</relationshipLabel>
        <relationshipName>Transactions</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Transaction_Date__c</fullName>
        <label>Transaction Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Debit</fullName>
                </value>
                <value>
                    <fullName>Credit</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Transaction</label>
    <nameField>
        <displayFormat>TX-{00000}</displayFormat>
        <label>TX Entry Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Transaction_Limit__c.object
<CustomObject>
    <fields>
        <fullName>Maximum_Debit_Allowed_per_Day__c</fullName>
        <label>Maximum Debit Allowed per Day</label>
        <precision>10</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Maximum_Debit_Allowed_per_Month__c</fullName>
        <label>Maximum Debit Allowed per Month</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Maximum_Debit_Allowed_per_Transaction__c</fullName>
        <label>Maximum Debit Allowed per Transaction</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Transaction Limit</label>
    <nameField>
        <label>Transaction Limit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transaction Limits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/EmailNotificationBatchClassTest.cls
/*
 * 	Description		:	To test if the batch class for sending monthly transaction mail to respective customers is working as expected.
 * 
 *  Code Coverage   :   97% 
 * 
 *  Created By		:	Soumi Chakraborty
 * 
 * 	Created Date	:	17/10/2022
 * 
 * 	Revision Logs	: 	V_1.0 - Created By - Soumi Chakraborty - 17/10/2022
 * */
@isTest
private class EmailNotificationBatchClassTest {
    
    @isTest static void sendMonthlyEmailTest(){
        Account personalAcc = new Account(Name='Axis Bank Account');
        insert personalAcc;
        
        Transaction_Limit__c sbiTxnLimit=new Transaction_Limit__c();
        sbiTxnLimit.Name='My Bank Limit';
        sbiTxnLimit.Maximum_Debit_Allowed_per_Day__c=11000.00;
        sbiTxnLimit.Maximum_Debit_Allowed_per_Month__c=160000.00;
        sbiTxnLimit.Maximum_Debit_Allowed_per_Transaction__c=5100.00;
        insert sbiTxnLimit;
    	
        List<Contact> contactListToInsert=new List<Contact>();
        
        for(Integer i=1;i<=2;i++){
            Contact con=new Contact(LastName='TestContact'+i,Email='testemail'+i+'@gml.com',AccountId=personalAcc.Id,StatusPicklist__c='Active',Available_Balance__c=5100.00,
                                  Transaction_Limit__c=sbiTxnLimit.Id );
            contactListToInsert.add(con);
        }
        insert contactListToInsert;
        List<Transaction_Entry__c> transactionsListToInsert=new List<Transaction_Entry__c>();
        for(Contact con: contactListToInsert){
            for(Integer i=1;i<=3;i++){
       
            Transaction_Entry__c newTransaction=new Transaction_Entry__c(Amount__c=456.00,Type__c='Credit',Status__c='Completed',
  		                                                                              		Transaction_Date__c=Date.today(),Contact__c=con.Id);
        	transactionsListToInsert.add(newTransaction);            
        	}
        }
        
        insert transactionsListToInsert;
        
        Test.startTest();
        EmailNotificationBatchClass obj = new EmailNotificationBatchClass();
        DataBase.executeBatch(obj); 
       	Test.stopTest();        
        
    }
}