src/objects/Transaction_Entry__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>14</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Transactions</relationshipLabel>
        <relationshipName>Transactions</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Transaction_Date__c</fullName>
        <label>Transaction Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Debit</fullName>
                </value>
                <value>
                    <fullName>Credit</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Transaction</label>
    <nameField>
        <displayFormat>TX-{00000}</displayFormat>
        <label>TX Entry Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Transaction_Limit__c.object
<CustomObject>
    <fields>
        <fullName>Maximum_Debit_Allowed_per_Day__c</fullName>
        <label>Maximum Debit Allowed per Day</label>
        <precision>10</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Maximum_Debit_Allowed_per_Month__c</fullName>
        <label>Maximum Debit Allowed per Month</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Maximum_Debit_Allowed_per_Transaction__c</fullName>
        <label>Maximum Debit Allowed per Transaction</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Transaction Limit</label>
    <nameField>
        <label>Transaction Limit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transaction Limits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TransactionControllerTest.cls
/*
 * 	Description		:	To test if the Transaction Controller class is returning data properly
 * 
 *  Code Coverage   :   97%
 * 
 *  Created By		:	Soumi Chakraborty
 * 
 * 	Created Date	:	15/10/2022
 * 
 * 	Revision Logs	: 	V_1.0 - Created By - Soumi Chakraborty - 15/10/2022
 * */
@isTest
private class TransactionControllerTest {
    
    @isTest static PageReference retriveTxnsAndSendEmailTest(){
        Account personalAcc = new Account(Name='Axis Bank Account');
        insert personalAcc;
        
        Transaction_Limit__c sbiTxnLimit=new Transaction_Limit__c();
        sbiTxnLimit.Name='My Bank Limit';
        sbiTxnLimit.Maximum_Debit_Allowed_per_Day__c=11000.00;
        sbiTxnLimit.Maximum_Debit_Allowed_per_Month__c=160000.00;
        sbiTxnLimit.Maximum_Debit_Allowed_per_Transaction__c=5100.00;
        insert sbiTxnLimit;
        
        Contact con= new Contact();
        con.LastName='TestContact23';
        con.Email='testemail12@gml.com';
        con.AccountId=personalAcc.Id;
        con.StatusPicklist__c='Active';
        con.Available_Balance__c=5100.00;
        con.Transaction_Limit__c=sbiTxnLimit.Id;
        insert con;
        List<Transaction_Entry__c> transactionsListToInsert=new List<Transaction_Entry__c>();
        String idOfLastContact;
        for(Integer i=0;i<10;i++){
       
            Transaction_Entry__c newTransaction=new Transaction_Entry__c(Amount__c=456.00,Type__c='Credit',Status__c='Pending',
  		                                                                              		Transaction_Date__c=Date.today().addDays(i),Contact__c=con.Id);
        	idOfLastContact=String.valueOf(con.Id);
        	transactionsListToInsert.add(newTransaction);      
        }
        insert transactionsListToInsert;
		Test.startTest();    
        TransactionController.sendEmailPdf(String.valueOf(Date.today()),String.valueOf(Date.today().addDays(5)),idOfLastContact);
        
        List<Transaction_Entry__c> returnedTransactionsAccToLimit=TransactionController.findTransactionsByContactId(con.Id,5);
        List<Transaction_Entry__c> returnedTransactionsAccToDate=TransactionController.findTransactionsByDateRange(con.Id,String.valueOf(Date.today()),String.valueOf(Date.today().addDays(20)));
        Test.stopTest();
        System.assertEquals(5, returnedTransactionsAccToLimit.size());
        System.assertEquals(10, returnedTransactionsAccToDate.size());
        String urlString = 'https://fexleservices5-dev-ed--c.visualforce.com/';
        String urlWithValues = urlString.substring(0, urlString.indexOf('.com/'));
        urlWithValues = urlWithValues+('.com/apex/TransactionPdfPage?id='+con.Id+'&startDate='+String.valueOf(Date.today())+'&endDate='+String.valueOf(Date.today().addDays(20)));            
        PageReference pageRef = new PageReference(urlWithValues);
        pageRef.setRedirect(true);
        
        Test.setCurrentPage(pageRef);
        TransactionController myObj =new TransactionController();
        myObj.generatePdf();
        return pageRef;
    }
}